In [1]:
import numpy as np
import pandas as pd


Exercicios:

    De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4]) faça a soma
    Faça a média
    Dada a matriz faça a soma das colunas X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
    Faça a média das linhas
    Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10]) Mostre o elemento de maior valor



In [2]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [3]:
np.sum(X)

43

In [4]:
np.mean(X)

4.777777777777778

In [5]:
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
c1 = np.sum(X[::,[0]])
c2 = np.sum(X[::,[1]])
c3 = np.sum(X[::,[2]])
c4 = np.sum(X[::,[3]])
print(c1,c2,c3,c4)

28 32 36 40


In [7]:
np.sum(X, axis=0)

array([28, 32, 36, 40])

In [8]:
np.mean(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [9]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
np.max(X)

10


Exercícios Aula 04

    Resete o INDEX do dataframe transformado ele em Coluna exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
    Crie um filtro para Kevin e Laura.
    Crie um filtro para todos que tiveram um numero de tentativa(attempts) mair que 2.
    Preencha os np.nan com 0.



In [10]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }

In [11]:
df = pd.DataFrame(exam_data)
df

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [12]:
df_reset = df.reset_index()
df_reset

index       name  score  attempts qualify
0      0  Anastasia   12.5         1     yes
1      1       Dima    9.0         3      no
2      2  Katherine   16.5         2     yes
3      3      James    NaN         3      no
4      4      Emily    9.0         2      no
5      5    Michael   20.0         3     yes
6      6    Matthew   14.5         1     yes
7      7      Laura    NaN         1      no
8      8      Kevin    8.0         2      no
9      9      Jonas   19.0         1     yes

In [14]:
filtro = df_reset[df_reset['name'].isin(['Kevin', 'Laura'])]
print(filtro)

   index   name  score  attempts qualify
7      7  Laura    NaN         1      no
8      8  Kevin    8.0         2      no


In [15]:
tentativas_maior_2 = df[df['attempts'] > 2]
tentativas_maior_2

name  score  attempts qualify
1     Dima    9.0         3      no
3    James    NaN         3      no
5  Michael   20.0         3     yes

In [17]:
df = df.fillna(0)
df

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    0.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    0.0         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes