In [5]:
import numpy as np

#Exercicios:
####
    #De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4]) faça a soma
    #Faça a média
    #Dada a matriz faça a soma das colunas X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
    #Faça a média das linhas
    #Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10]) Mostre o elemento de maior valor
#####

X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X


array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [6]:
np.sum(X)

43

In [14]:
np.mean(X)


3.7

In [15]:
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
c1 = np.sum(X[::,[0]])
c2 = np.sum(X[::,[1]])
c3 = np.sum(X[::,[2]])
c4 = np.sum(X[::,[3]])
print(c1,c2,c3,c4)


28 32 36 40


In [19]:
np.sum(X, axis=0)

array([28, 32, 36, 40])

In [20]:
l1 = np.mean(X[[0],::])
l2 = np.mean(X[[1],::])
l3 = np.mean(X[[2],::])
l4 = np.mean(X[[3],::])
print(l1,l2,l3,l4)



2.5 6.5 10.5 14.5


In [12]:
np.mean(X, axis=1)


array([ 2.5,  6.5, 10.5, 14.5])

In [13]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
np.max(X)

10